### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by AlexMog** [Kamik423/2mF#1]
Hey!
I found your repository by your youtube video presenting it, and so I am trying to make your script work for my own ships.
But, there are some problems (sometimes, the target never arrives at the good landing position (and so the "BREAK" never stops) and I don't understand the variable here: https://github.com/Kamik423/2mF/blob/master/planarBoostback.ks#L2 (the k Parameter).
(I assumed that the problem comes frome here).

Thanks again for all of this, I am learning much things with it :)
Regards.

**Comment by Kamik423** [comment]
That is a coefficient of friction I have to set manually, it is used for all flight calculations. It is kind of unfortunate, that I have to set it myself, I’d much rather have it be dynamic. That’s why I started [project athena](https://github.com/Kamik423/athena), however I had to stop due to some technical problem and lack of time.

You will have to change it manually until it works, I am sorry. Higher k assumes the booster has more friction and will thus fly farther over the landing site and brake later, Lower k assumes the booster has less friction, boost not so far, and break earlier. Find a value that works for you.

Keep on flying and thanks for the interest!
